#
# Copyright 2022-2026 Chartbeat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

FROM ubuntu:24.04

RUN apt update && apt-get install -y perl python3 python3-pip git unzip curl zip make build-essential

# Make `python` resolve to python3 (so `#!/usr/bin/env -S python` works).
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1

RUN mkdir -p /app/code-golf
RUN useradd -d /app -s /bin/bash app && chown -R app:app /app
WORKDIR /app
USER app

RUN curl -s "https://get.sdkman.io" | bash
RUN bash -c "source /app/.sdkman/bin/sdkman-init.sh && sdk install java 22-open && sdk install scala"

# Warm up Scala compilation server by creating and running a simple program
RUN bash -c "source /app/.sdkman/bin/sdkman-init.sh && echo 'object H extends App {println(\"hello, world\")}' > /tmp/warmup.scala && scala /tmp/warmup.scala && rm /tmp/warmup.scala"

# Install nvm and Node.js LTS
ENV NVM_DIR="/app/.nvm"
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
RUN bash -c "source $NVM_DIR/nvm.sh && nvm install --lts && nvm use --lts && nvm alias default lts/*"

RUN git clone https://github.com/rakudo/rakudo.git /app/rakudo
ENV PATH="${PATH}:/app/rakudo/install/bin:/app/rakudo/install/share/perl6/site/bin"
RUN echo "--gen-moar --backends=moar --make-install" > /app/rakudo/config.default
RUN cd /app/rakudo && perl Configure.pl
